@startuml pizzaburger service

skinparam Linetype ortho
hide circle

class Sessions {
    -id : int [PK] <<generated>>
    -user_id : int [FK]
}

class User {
    -id : int [PK] <<generated>>
    -name : varchar
    -email : varchar
    -password : varchar
    -address: varchar
}

class Cart {
    -id : int [PK] <<generated>>
    -user_id : int [FK]
}

class Restaurant {
    -id : int [PK] <<generated>>
    -name : varchar
}

class Review {
    -id : int [PK]  <<generated>>
    -user_id : int [FK]
    -order_pizza_id : int [FK]
    -content : varchar
}

class Pizza {
    -id : int [PK]  <<generated>>
    -restaurant_id : int [FK]
    -type : PizzaType
    -price : float
    -image : varchar
    -rating : float
}


class Order {
    -id : int [PK]  <<generated>>
    -user_id : int [FK]
}

enum PizzaType {
  HAM
  CHEESE
  VEGGIE
  EXTRA
}

class OrderPizza {
    -id : int [PK]  <<generated>>
    -order_id : int [FK]
    -pizza_id : int [FK]
    -quantity : int
    -review_id : int [FK]
}

class CartPizza {
    -id : int [PK]  <<generated>>
    -cart_id : int [FK]
    -pizza_id : int [FK]
    -quantity : int
}

' Define relationships
User ||..|| Cart : "user_id [FK]"

User ||..o{ Order : "user_id [FK]"
User ||..o{ Review : "user_id [FK]"

Pizza ||..o{ OrderPizza : "pizza_id [FK]"
Order ||..o{ OrderPizza : "order_id [FK]"

Restaurant ||..o{ Pizza : "restaurant_id [FK]"

Cart ||..o{ CartPizza : "cart_id [FK]"
Pizza ||..o{ CartPizza : "pizza_id [FK]"

Review ||..|| OrderPizza : "review_id [FK]"
@enduml
